-- Create fixed_rates table
CREATE TABLE IF NOT EXISTS fixed_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rate_type TEXT NOT NULL CHECK (rate_type IN ('condo', 'reserve')),
  billing_method TEXT NOT NULL CHECK (billing_method IN ('fixed', 'prorated')),
  expense_type TEXT NOT NULL CHECK (expense_type IN ('ordinary', 'extraordinary')),
  amount DECIMAL(10, 2) NOT NULL,
  effective_date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add RLS policies
ALTER TABLE fixed_rates ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all operations for authenticated users
CREATE POLICY "Enable all operations for authenticated users" ON fixed_rates
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);
