
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzlidefxxfoacoyfyaat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6bGlkZWZ4eGZvYWNveWZ5YWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2OTc1MzIsImV4cCI6MjA1NjI3MzUzMn0.s5k8WK6Q664AqwxnoXXTtShB09uHsbjRo0ujHmS7ggw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
